### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by presingjos** [presingjos/jarvis#1]
- [x] Implement simple record to string 
- [ ] Enable active listening
- [ ] Enable actions
- [ ] Speed up model interference (the first inference is always slower. Seeing x1.4 speeds)
- [ ] Create DNN for string -> action interaction
- [ ] Port to linux (enable for Raspberry Pi 3)
